name: deploy to bluegreen

on:
  workflow_dispatch:
  pull_request:
    branches: [ "Patch4" ]  

permissions:
  actions: read
  contents: read

jobs:
  deployasbluegreen:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Manual deploy step
        run: |
          echo "Manually triggered deployment!"
