name: deploy to greenblue

on:
  workflow_dispatch:

  push:
   branches: [ "Patch4" ]

permissions:
  actions: read
  contents: read

jobs:
  deploytogreen:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Green deploy
        run: |
          echo "Manual deployment!"
