name: deploy to bluegreen

on:
  workflow_dispatch:

  push:
   branches: [ "Patch4" ]

  pull_request:
    branches: [ "Patch4" ]

permissions:
  actions: read
  contents: read

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Manual deploy step
        run: |
          echo "Manually triggered deployment!"
      - name: dummy
        run: lets
